name: Update M3U File

on:
  workflow_dispatch:  # Manuel olarak çalıştırılabilir
  schedule:
    - cron: '*/5 * * * *'  # Her 5 dakikada bir çalıştır

jobs:
  update-m3u:
    runs-on: self-hosted  # Self-hosted runner kullanılıyor

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Depoyu çek
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cloudscraper
        
    - name: Run script.py to update M3U
      run: python script.py  # M3U dosyasını güncelle

    - name: Run script to update M3U file
      run: |
          git add channels_vavoo.m3u
          git diff --cached --quiet || git commit -m "Update channels_vavoo.m3u file"
          git push
      shell: bash
