name: Run Scripts and Generate M3U

on:
  push:
    branches:
      - main  # Workflow'un çalışacağı branch
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  build:
    runs-on: windows-latest  # Windows ortamında çalışacak

    steps:
      # Depoyu klonla
      - name: Checkout code
        uses: actions/checkout@v2

      # Python ortamını kur
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Python bağımlılıklarını kur (eğer varsa requirements.txt dosyası)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # script.py dosyasını çalıştır
      - name: Run script.py
        run: |
          python script.py

      # 2_any_country_dnsredir.cmd dosyasını çalıştır
      - name: Run 2_any_country_dnsredir.cmd
        run: |
          ./2_any_country_dnsredir.cmd

      # Dosya oluşumu kontrolü
      - name: Check 
