name: Update M3U8 Links and Shorten URLs

on:
  schedule:
    - cron: '*/30 * * * *' # Her 30 dakikada bir çalışacak
  workflow_dispatch: # Manuel olarak çalıştırılabilir

jobs:
  update-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install cloudscraper

      - name: Run update script
        run: python update_m3u8_links.py

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add channels_vavoo.m3u
          git commit -m "Update M3U8 links"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
