name: Update M3U File

on:
  schedule:
  - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch: # Manuel tetikleme desteği
    
  push:
    branches:
      - main

jobs:
  update_m3u:
    runs-on: self-hosted  # self-hosted runner kullanımı

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update M3U file
        run: |
          python script.py   # script.py dosyanızın M3U güncellemesini çalıştıracak

      - name: Commit and push changes if M3U file updated
        run: |
          # Eğer script.py dosyasındaki M3U dosyası güncellenmişse, push et
          git add channels_vavoo.m3u
          git commit -m "Update channels_vavoo.m3u file" || echo "No changes to commit"
          git push
