name: Update M3U File

on:
  schedule:
  - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch: # Manuel tetikleme desteği
    
  push:
    branches:
      - main

jobs:
  update_m3u:
    runs-on: self-hosted  # self-hosted runner kullanımı

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cloudscraper

      - name: Update M3U file
        run: |
          python script.py   # script.py dosyanızın M3U güncellemesini çalıştıracak

      # Git işlemi (commit ve push işlemi)
      - name: Commit and push M3U file if updated
        shell: powershell
        run: |
          git add channels_vavoo.m3u
          git diff --cached --quiet  
          if ($?) {
         echo "No changes detected."
         } else {
         git commit -m "Update channels_vavoo.m3u file"
         }
          git push
