name: Update M3U File

on:
  schedule:
    - cron: '0 21 * * *'  # UTC'de her gün saat 21:00'de çalışır, bu Türkiye saatiyle 00:00'a denk gelir
  workflow_dispatch: # Manuel tetikleme desteği

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python script.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add index.m3u
        git commit -m "Update index.m3u file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
