name: Update M3U and Run Scripts

on:
  push:
    branches:
      - main

jobs:
  update_m3u:
    runs-on: windows-latest  # Windows ortamında çalışacak
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cloudscraper

      - name: Run CMD and Python Sequentially
        run: |
          # CMD dosyasını başlatıyoruz
          start-process cmd -ArgumentList '/c', 'start', '2_any_country_dnsredir.cmd' 
          # CMD dosyasının tam olarak başlamasını bekliyoruz
          sleep 5
          # Python dosyasını başlatıyoruz
          python script.py
          
      - name: Wait for channels_vavoo.m3u file to be created
        run: |
          echo "Waiting for channels_vavoo.m3u file to be created"
          while [ ! -f channels_vavoo.m3u ]; do
            sleep 10
          done
          echo "File channels_vavoo.m3u created successfully"
