name: Run Scripts and Generate M3U

on:
  push:
    branches:
      - main  # Workflow'un çalışacağı branch
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  build:
    runs-on: windows-latest  # Windows ortamında çalışacak

    steps:
      # Depoyu klonla
      - name: Checkout code
        uses: actions/checkout@v2

      # Python ortamını kur
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Python bağımlılıklarını kur (eğer varsa requirements.txt dosyası)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    - name: Run EXE and Python Script
      run: |
        # EXE dosyasını çalıştırma
        ./2_any_country_dnsredir.cmd & 
        # Python dosyasını çalıştırma
        python script.py

      # Dosya oluşumu kontrolü
      - name: Check if channels_vavoo.m3u was created
        run: |
          if (Test-Path -Path "channels_vavoo.m3u") {
            Write-Host "channels_vavoo.m3u dosyası başarıyla oluşturuldu."
          } else {
            Write-Host "channels_vavoo.m3u dosyası oluşturulamadı."
            exit 1
          }
