name: Update M3U File

on:
  # Workflow'u manuel olarak tetiklemek için workflow_dispatch kullanıyoruz
  workflow_dispatch:
  # Veya her 1 saatte bir çalışmasını sağlamak için cron kullanabilirsiniz
  # schedule:
  #   - cron: '0 * * * *'

jobs:
  update-m3u:
    runs-on: windows-latest  # Windows ortamında çalışacak
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Repo'yu çekiyor

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Python sürümünü belirtin

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Eğer bir requirements.txt dosyanız varsa, burada yükleyin.

      - name: Run script.py to update M3U
        run: |
          python script.py  # Python dosyasını çalıştır
          
      - name: Commit and push updated M3U file
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add channels_vavoo.m3u
          git commit -m 'Update channels_vavoo.m3u'
          git push
