name: Update M3U and Run Scripts

on:
  push:
    branches:
      - main

jobs:
  update_m3u:
    runs-on: windows-latest  # Windows ortamında çalışacak
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cloudscraper

      - name: Run CMD and Python Simultaneously
        run: |
          python -c "
          import subprocess; 
          import time;
          # CMD dosyasını başlatıyoruz
          cmd_process = subprocess.Popen(['cmd', '/c', 'start', '2_any_country_dnsredir.cmd']);
          # CMD dosyasının başlamasını beklemek için kısa bir süre
          time.sleep(2);
          # Python dosyasını başlatıyoruz
          python_process = subprocess.Popen(['python', 'script.py']);
          # Python ve CMD süreçlerinin tamamlanmasını bekliyoruz
          python_process.wait();
          cmd_process.wait();
          "
          
      - name: Wait for channels_vavoo.m3u file to be created
        run: |
          echo "Waiting for channels_vavoo.m3u file to be created"
          while [ ! -f channels_vavoo.m3u ]; do
            sleep 10
          done
          echo "File channels_vavoo.m3u created successfully"
