name: Update M3U8 Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *' # Her 30 dakikada bir çalışır
  workflow_dispatch: # Manuel olarak çalıştırma seçeneği

jobs:
  update-m3u8:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Python script
        run: python script.py

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add github_pages/
          git commit -m "Update M3U8 files"
          git push
