name: Update M3U File

on:
  workflow_dispatch:  # Manuel olarak çalıştırılabilir
  schedule:
    - cron: '*/5 * * * *'  # Her 5 dakikada bir çalıştır
  push:
   branches:
      - main  # Ana dalda değişiklik yapıldığında tetiklenir

jobs:
  update_m3u:
    runs-on: windows-latest  # Windows ortamında çalışacak

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3  # Repository'yi check-out yap

      - name: List files in the repository (for debugging)
        run: dir  # Dosyaların bulunduğu dizini kontrol edin

      - name: Set up Python
        uses: actions/setup-python@v4  # Python ortamını kur
        with:
          python-version: '3.x'  # Python sürümünü ihtiyacınıza göre belirleyin,

      - name: Install dependencies
        run: |
         pip install cloudscraper

      - name: Run CMD script and Python script in parallel
        run: |
          2_any_country_dnsredir.cmd && python script.py

      - name: Run script to update M3U file
        run: |
          git add channels_vavoo.m3u
          git diff --cached --quiet || git commit -m "Update channels_vavoo.m3u file"
          git push
        shell: bash
